#! /usr/bin/env python
# Uses ROS param parser to pull in injection from XML and event id, then print parameters.  Currently used to popuate mass1, mass2, event time

import ourparams
import lal
import numpy as np
import sys
opts,  rosDebugMessagesDictionary = ourparams.ParseStandardArguments()

Psig = ourparams.PopulatePrototypeSignal(opts)

if (opts.template_mass1):
   print Psig.m1/lal.LAL_MSUN_SI
   sys.exit(0)
if (opts.template_mass2):
   print Psig.m2/lal.LAL_MSUN_SI
   sys.exit(0)
if (opts.signal_tref):
   print float(Psig.tref)
   sys.exit(0)
