#!/usr/bin/env python
import sys
import math

import sqlite3

# Stolen from gstlal_inspiral_plotsummary
sim_coinc_map = """
CREATE TEMPORARY TABLE
    sim_coinc_map
AS
    SELECT
        sim_inspiral.simulation_id AS simulation_id,
        (
            SELECT
                coinc_inspiral.coinc_event_id
            FROM
                coinc_event_map AS a
                JOIN coinc_event_map AS b ON (
                    b.coinc_event_id == a.coinc_event_id
                )
                JOIN coinc_inspiral ON (
                    b.table_name == 'coinc_event'
                    AND b.event_id == coinc_inspiral.coinc_event_id
                )
            WHERE
                a.table_name == 'sim_inspiral'
                AND a.event_id == sim_inspiral.simulation_id
            ORDER BY
                coinc_inspiral.false_alarm_rate
            LIMIT 1
        ) AS coinc_event_id
    FROM
        sim_inspiral
    WHERE
        coinc_event_id IS NOT NULL
"""

select_coincs = """
SELECT
    -- sim_inspiral.*,
    -- sngl_inspiral.*
    sngl_inspiral.ifo, sngl_inspiral.mass1, sngl_inspiral.mass2, sngl_inspiral.snr
FROM
    sim_inspiral
    JOIN sim_coinc_map ON (
        sim_coinc_map.simulation_id == sim_inspiral.simulation_id
    )
    JOIN coinc_event_map ON (
        coinc_event_map.coinc_event_id == sim_coinc_map.coinc_event_id
    )
    JOIN sngl_inspiral ON (
        coinc_event_map.table_name == 'sngl_inspiral'
        AND coinc_event_map.event_id == sngl_inspiral.event_id
    )
    WHERE sngl_inspiral.snr > 4.0 and sim_inspiral.simulation_id == "sim_inspiral:simulation_id:%d"
""" % int(sys.argv[2])

connection = sqlite3.connect(sys.argv[1])
connection.execute(sim_coinc_map)
net_snr = 0
for ifo, m1, m2, snr in connection.execute(select_coincs):
    net_snr += snr**2

print m1, m2, math.sqrt(net_snr)
