#!/usr/bin/env python
import sys
from collections import defaultdict

import matplotlib
matplotlib.use("Agg")
from matplotlib import pyplot

import numpy

from pylal.series import read_psd_xmldoc
from glue.ligolw import utils

psdd = defaultdict(list)
ifo = sys.argv[1]
for arg in sys.argv[2:]:
    print arg
    psdd[arg] = read_psd_xmldoc(utils.load_filename(arg))[ifo]

pyplot.figure()
pyplot.title(ifo)
for fname, series in psdd.iteritems():
    pyplot.loglog()
    f = numpy.arange(series.f0, len(series.data)*series.deltaF, series.deltaF)
    pyplot.plot(f, series.data, '-', label=fname)
    pyplot.xlim([1e1,8e3])
    pyplot.ylim([1e-46,1e-26])
    #pyplot.ylim([1e15,1e18])

pyplot.grid()
pyplot.legend()

pyplot.savefig("psd_single.png")
